[tools."github:elm/compiler"]
version = "0.19.1"
rename_exe = "elm.exe"

[tools."github:elm/compiler".platforms.windows-arm64]
asset_pattern = "binary-for-windows-64-bit.gz"
checksum = "sha256:d1bf666298cbe3c5447b9ca0ea608552d750e5d232f9845c2af11907b654903b"
